# Generated by Django 5.2.4 on 2025-08-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_chamado_atualizado_em_chamado_prioridade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='anexos/'),
        ),
    ]
